# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: me
  pool: 5
  timeout: 5000
  username: root
  password: abcd1234

staging:
  adapter: mysql2
  database: beehive_staging
  pool: 5
  timeout: 5000
  username: root
  password: admin

test:
  adapter: mysql2
  database: beehive_test
  pool: 5
  timeout: 5000
  username: root
  password: root
